<?php return array (
  'email_type' => '1',
  'email_safe' => '',
  'mail_address' => '',
  'smtp' => '',
  'smtp_user' => '',
  'smtp_pwd' => '',
  'smtp_port' => '',
  'order_by' => 'new',
  'order_type' => 'asc',
  'list_type' => 'win',
  'auto_finish' => '1',
  'index_slide' => 'a:2:{i:0;a:3:{s:4:"name";s:11:"high,延安";s:3:"url";s:20:"http://www.baidu.com";s:3:"img";s:39:"upload/2016/11/12/20161112070857522.jpg";}i:1;a:3:{s:4:"name";s:12:"真的很好";s:3:"url";s:20:"http://www.baidu.com";s:3:"img";s:39:"upload/2016/11/12/20161112070907962.jpg";}}',
  'name' => 'high,延安',
  'url' => 'http://www.baidu.com',
  'master' => '',
  'qq' => '',
  'email' => '',
  'mobile' => '',
  'phone' => '',
  'address' => '',
  'site_footer_code' => '<div class="footer" style="text-align:center"><p class="links"><a href="">关于我们</a>|<a href="">常见问题</a>|<a href="">安全交易</a>|<a href="">购买流程</a>|<a href="">如何付款</a>|<a href="">联系我们</a>|<a href="">合作提案</a></p><p class="copyright">Powered by <a href="http://www.aircheng.com">iWebShop</a></p>Copyright © 2005-2014 <a class="copyys" target="_blank" href="http://www.miibeian.gov.cn/">鲁ICP备01000010号</a></div>',
  'tax' => '10',
  'stockup_time' => '1',
  'index_seo_title' => 'high,延安',
  'index_seo_keywords' => 'high,延安',
  'index_seo_description' => 'high,延安',
  'goods_no_pre' => 'SD',
)?>